Smeagol forcage
meteofrance/py4cast pull request #28
Opened 2024-09-16 13:40 UTC by CorentinSeznec

Adding smeagol forcing. Instead of reading variables "SOMMFLU.RAY.SOLA", "SOMMRAYT.SOLAIRE" in the json, creating them in the fly.

2024-09-17 07:03 UTC, colon3ltocard commented on py4cast/datasets/smeagol.py
> +    def generate_toa_radiation_forcing(self, sample: Sample):
This function could be useful and desired with any dataset, have you considered moving it to datasets/base.py ?

2024-09-17 07:06 UTC, colon3ltocard commented on py4cast/datasets/smeagol.py
> +    def generate_toa_radiation_forcing(self, sample: Sample):
ALso this kind of very calculatory isolated functions are ideal candidate for unit tests ! consider adding one ?

2024-09-17 07:24 UTC, colon3ltocard commented on py4cast/datasets/smeagol.py
> +    def generate_toa_radiation_forcing(self, sample: Sample):
The function could be decoupled from the Sample object by taking directly two 'simple' arguments: day_of_year and hour_of_day.

Dataset maintainers could then choose to use it or not, and how they plug it with their sample implementation.

@CorentinSeznec for unit test example: https://github.com/meteofrance/py4cast/blob/main/tests/test_datasets.py

2024-09-24 09:00 UTC, LBerth requested changes
Hi ! Good job !
There is a small issue with where you put your forcing methods : I don't think there is a need to put them in the dataset base class and an independant module would be more appopriate and keep things decoupled.

2024-09-24 09:00 UTC, LBerth commented on py4cast/datasets/base.py
> +        )  # (sample_len,)
Can you check the `get_year_hour_forcing` method in Titan ? I've made a modification to compute the number of days in a year, including leap years. So we can stop using the variable `SECONDS_IN_YEAR` which doesn't account for leap years.

2024-09-24 09:00 UTC, LBerth commented on py4cast/datasets/titan/__init__.py
> +        item = sample.load(lforcings)
Hi ! I'd prefer if you would put the solar forcing in the `Sample.load` method, so that the Sample class contains everything it need to load.

2024-09-24 09:00 UTC, LBerth commented on py4cast/datasets/base.py
Your methods to compute the solar forcing don't use any of the attributes or methods of the Dataset base class. I'd prefer if we decoupled those methods from the dataset. For instance, you could create a `py4cast/date_utils.py` module containing all the date and solar forcing methods.

2024-09-24 09:00 UTC, LBerth commented on tests/test_datasets.py
> +
See my first comment: if you decouple the forcing methods from the dataset class, you won't need to create these fake dataset and fake grid.

2024-09-24 09:03 UTC, colon3ltocard commented
> Hi ! Good job ! There is a small issue with where you put your forcing methods : I don't think there is a need to put them in the dataset base class and an independant module would be more appopriate and keep things decoupled.

I agree with @LBerth , a python function decoupled from the dataset base would be also more easily unit testable. It is really a "computing physical stuff function" which does not belong in dataset base.

2024-09-25 07:42 UTC, colon3ltocard commented on py4cast/forcingutils/utils.py
Nice work ! 

Only one minor comment: I would just make a single **forcingutils.py** module (single Python file, keep it simple) for now. There is no need to make packages for everything upfront.  Also you can add a docstring at the top of the module to explain its purpose.

Also **forcingutils/utils.py** is quiet a redundant name if I may.

2024-09-25 07:42 UTC, colon3ltocard commented on py4cast/lightning.py
I don't think lightning.py requires any modification since we fixed several bugs related to Metrics over the last few days ?

2024-09-25 07:52 UTC, LBerth commented on py4cast/forcingutils/utils.py
As you have only one file with forcing utilitaries (and I don't think we'll have more in the short term), you don't have to put it in a new folder. You can just put a `forcingutils.py` file in the `py4cast` module, next to the `lightning.py` file.
In the datasets, the import will be `from py4cast.forcingutils import ...`.

2024-09-25 07:57 UTC, LBerth commented on py4cast/lightning.py
@colon3ltocard do these changes conflict with other ongoing PR ?

2024-09-25 08:01 UTC, colon3ltocard commented on py4cast/lightning.py
no but I don't think there should be any change to the lightning module.

2024-09-25 10:58 UTC, LBerth approved these changes

2024-09-25 12:42 UTC, colon3ltocard approved these changes

2024-09-25 12:42 UTC, merged